name: Run Postman API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 4. Run Postman Tests
      - name: Run API Tests
        run: |
          newman run ./Portal_Socios_API.postman_collection.json \
            -e ./Portal_Socios_API.postman_environment.json \
            --folder "Pruebas Exploratorias (PRODUCCION)" \ 
            --reporters cli,junit \
            --reporter-junit-export results.xml
